spring:
  cloud:
    sentinel:
      transport:
        port: 7006 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8858 # 指定控制台服务的地址
    stream:
      kafka:
        binder:
          # kafka集群
          brokers: localhost:9092
      bindings:
        # 输出通道
        message-output:
          # topic
          destination: message
          contentType: application/octet-stream
  redis:
    # Redis服务器地址
    host: localhost
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 最大连接数，负值表示没有限制，默认8
        max-active: 20
        # 最大阻塞等待时间，负值表示没限制，默认-1
        max-wait: -1
        # 最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接，默认0
        min-idle: 0

# 开启SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

netty:
  bossThreadNum: 0
  workerThreadNum: 0
  businessCorePoolSize: 200
  businessMaxPoolSize: 300
  businessMaxKeepAliveTime: 30
  port: 8005

redis:
  database: chatService
  separator: ":"
  onlineUser:
    key: 'onlineUser'
