server:
  port: 8004
spring:
  cloud:
    sentinel:
      transport:
        port: 7005 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8858 # 指定控制台服务的地址
    stream:
      kafka:
        binder:
          # kafka集群
          brokers: localhost:9092
#      bindings:
#        # 输出通道
#        register-email-input:
#          group: sms
#          # topic
#          destination: register-email
#          contentType: text/plain

#          consumer:
#            partitioned: true
#      instance-count: 1
#      instance-index: 0
# 开启SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
