server:
  port: 9901
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: group
          uri: lb://group
          predicates:
            - Path=/group/**
          filters:
            - StripPrefix=1
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: media
          uri: lb://media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1
        - id: chat
          uri: lb:ws://chat
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: gateway
          uri: lb:ws://gateway
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        port: 7002 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8858 # 指定控制台服务的地址
    stream:
      kafka:
        binder:
          # kafka集群
          brokers: localhost:9092
      bindings:
        # 输入通道
        push-message-input:
          group: gateway
          # topic
          destination: pushMessage
          contentType: application/octet-stream
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.txt
  redis:
    # Redis服务器地址
    host: localhost
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 最大连接数，负值表示没有限制，默认8
        max-active: 20
        # 最大阻塞等待时间，负值表示没限制，默认-1
        max-wait: -1
        # 最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接，默认0
        min-idle: 0
secure:
  ignore:
    urls: # 配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/user/register"
      - "/user/code"
      - "/user/check-exist/**"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  onlineUsers:
    key: 'users:online'