version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - ../../../data/mysql/data/db:/var/lib/mysql #数据文件挂载
      - ../../../data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - ../../../data/mysql/log:/var/log/mysql #日志文件挂载
  redis:
    image: redis:5.0.9
    container_name: redis
    restart: always
    command: redis-server
    volumes:
      - ../../../data/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    ports:
      - 8848:8848
    volumes:
      - ../../../data/nacos/logs:/home/nacos/logs
      - ../../../data/nacos/init.d/customer.properties:/home/nacos/init.d/customer.properties
    environment:
      JVM_XMS: "256M"
      JVM_XMX: "256M"
      MODE: standalone
    restart: always
    depends_on:
      - mysql
  zookeeper:
    image: zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP} # 宿主机ip
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092 # 宿主机ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    depends_on:
      - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka_manager
    environment:
      ZK_HOSTS: ${HOST_IP} # 修改为自己宿主机ip
    ports:
      - 9000:9000
    restart: always
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - "TAKE_FILE_OWNERSHIP=true"
    volumes:
      - ../../../data/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.9.3
    container_name: logstash
    restart: always
    volumes:
      - ../../../data/logstash/logstash-template.conf:/usr/share/logstash/pipeline/logstash-template.conf
    depends_on:
      - elasticsearch
      - kafka
  kibana:
    image: kibana:7.9.3
    container_name: kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - 5601:5601
#  nginx:
#    image: nginx:1.10
#    container_name: nginx
#    volumes:
#      - ../../../data/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
#      - ../../../data/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
#      - ../../../data/nginx/log:/var/log/nginx #日志文件挂载
#    ports:
#      - 80:80